feat/despliegue en OCI

diff --git a/.github/workflows/cicd-workflow.yaml b/.github/workflows/cicd-workflow.yaml
--- a/.github/workflows/cicd-workflow.yaml
+++ b/.github/workflows/cicd-workflow.yaml
@@ -7,8 +7,163 @@ jobs:
   build-job:
     name: Build Job
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Start build job
+    - name: 'Checkout' #descarga nuestro code en la VM
+      uses: actions/checkout@v5.0.0
+
+    - name: 'Setup Java JDK' #descarga un JDK en la VM
+      uses: actions/setup-java@v5.0.0
+      with:
+        java-version: 21
+        distribution: 'temurin'
+
+    - name: 'Check Java Version'
+      run: |
+        java --version
+
+    - name: 'Start build job'
       run: |
         echo "Starting the build job"
+
+    - name: 'Run Tests'
+      run: |
+          # Dar permisos primero
+          chmod +x ./gradlew
+          ./gradlew test
+    - name: 'Publish Test Report'
+      if: always()
+      uses: actions/upload-artifact@v6.0.0
+      with:
+        name: 'test-report'
+        path: build/reports/tests/test/*
+
+    # crea JAR file con ./gradlew assemble,place in build/libs
+    - name: 'Assemble JAR'
+      run: |
+        ./gradlew assemble
+
+    - name:  'Get Version Number'
+      run: |
+        echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
+
+    - name: 'Publish JAR'
+      uses: actions/upload-artifact@v6.0.0
+      with:
+        name: 'cicd-demo-${{env.VERSION}}-all.jar'
+        path: build/libs/*-all.jar
+
+    - name: 'Write Config & key files'
+      run: |
+        mkdir ~/.oci
+        echo "[DEFAULT]" >> ~/.oci/config
+        echo "user=${{secrets.OCI_USER_OCID}}" >>
+        ~/.oci/config
+        echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >>
+        ~/.oci/config
+        echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >>
+        ~/.oci/config
+         echo "region=${{secrets.OCI_REGION}}" >>
+        ~/.oci/config
+        echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >>
+        ~/.oci/config
+        echo "key_file=~/.oci/key.pem" >> ~/.oci/config
+        echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
+        echo "${{secrets.VM_SSH_PUB_KEY}}" >> /home/runner/.oci/
+        id_vm.pub
+    - name: 'Install OCI CLI'
+      run: |
+        curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
+        chmod +x install.sh
+        ./install.sh --accept-all-defaults
+        echo "/home/runner/bin"  >> $GITHUB_PATH
+        exec -l $SHELL
+    - name: 'Fix Config File Permissionis'
+      run: |
+        oci setup repair-file-permissions --file /home/runner/.
+        oci/config
+        oci setup repair-file-permissions --file /home/runner/.
+        oci/key.pem
+    #si existe VM en ejecucion, tomara su OCID para reutilizarlo
+    - name: 'Check existing instance'
+      run: |
+        echo "INSTANCE_OCID=$(\
+        oci compute instance list \
+        --lifecycle-state RUNNING \
+        --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
+        --diplay-name cicd-demo \
+        --query "data[0].id" \
+        --raw-output \
+        )" >> $GITHUB_ENV
+    #si no existe, creamos una nueva OCI con la config especificada
+    - name: 'Create instance'
+      if: ${{!env.INSTANCE_OCID}}
+      run: |
+        echo "INSTANCE_OCID=$( \
+          -c ${{secrets.VM_COMPARTMENT_OCID}} \
+          --availability-domain ${{secrets.VM_AVAILABILITY_
+          DOMAIN}} \
+          --shape ${{secrets.VM_SHAPE}} \
+          --shape-config '{"memoryInGBs": 4,"ocpus":1}' \
+          --assign-public-ip true \
+          --display-name cicd-demo \
+          --image-id ${{secrets.VM_CUSTOM_IMAGE_OCID}} \
+          --ssh-authorized-keys-file /home/runner/.oci/id_vm.pub \
+          --subnet-id ${{secrets.VM_SUBNET_OCID}} \
+          --wait-for-state  RUNNING \
+          --query "data.id" \
+          --raw-output \
+        )" >> $GITHUB_ENV
+    #obtenemos ip publica p/conectarnos via SSH/SCP
+    - name: 'Get Instance IP'
+      run: |
+        echo "INSTANCE_IP=$( \
+        oci compute instance list-vnics \
+        --instance-id ${{env.INSTANCE_OCID}} \
+        --query 'data [0]."public-ip"' \
+        --raw-output \
+        )" >> $GITHUB_ENV
+    #esperar a que el servicio este disponible el servicio ssh, puede tardar
+    - name: 'Wait for SSH'
+      run: |
+        while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
+        sleep 5
+        echo "SSH not available..."
+        done; echo "SSH ready!"
+    #conecta por SSH la VM, detenemos cualquier instancia previa de la app
+    - name: 'Stop App'
+      uses: appleboy/ssh-action@v0.1.4
+      with:
+        host: ${{env.INSTANCE_IP}}
+        username: opc
+        key: ${{secrets.VM_SSH_PRIVATE_KEY}}
+        script: |
+          pid=`ps aux | grep "[c]icd-demo.jar" | awk '{print $2}'`
+          if [ "$pid" == "" ]; then
+          echo "Process not found"
+          else
+          kill -9 $pid
+          fi
+          sudo mkdir -p /app
+    #transferimos el jar file desde el runner a la VM
+    - name: 'Push JAR'
+      uses: appleboy/scp-action@v0.1.4
+      with:
+        host: ${{ env.INSTANCE_IP }}
+        username: opc
+        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+        source: "build/libs/cicd-demo-${{env.VERSION}}-all.jar"
+        target: "app"
+        strip_components: 2
+    # movemos jar a su ubicacion final y lo ejecutamos en background con nohup
+    - name: 'Start App'
+      uses: appleboy/ssh-action@v0.1.4
+      with:
+        host: ${{ env.INSTANCE_IP }}
+        username: opc
+        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+        script: |
+          sudo mv ~/app/cicd-demo-${{env.VERSION}}-all.jar /app/
+          cicd-demo.jar
+          nohup java -jar /app/cicd-demo.jar > output.$
+          (date --iso).log 2>&1 &
